//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using NHibernate.Criterion;
using NHibernate.SqlCommand;
using NHibernate.Transform;

namespace NHibernate
{
	using System.Threading.Tasks;
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial interface ICriteria : ICloneable
	{

		/// <summary>
		/// Get the results
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <returns></returns>
		Task<IList> ListAsync(CancellationToken cancellationToken = default(CancellationToken));

		/// <summary>
		/// Convenience method to return a single instance that matches
		/// the query, or null if the query returns no results.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <returns>the single result or <see langword="null" /></returns>
		/// <exception cref="HibernateException">
		/// If there is more than one matching result
		/// </exception>
		Task<object> UniqueResultAsync(CancellationToken cancellationToken = default(CancellationToken));

		#region NHibernate specific

		/// <summary>
		/// Get the results and fill the <see cref="IList{T}"/>
		/// </summary>
		/// <param name="results">The list to fill with the results.</param>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <typeparam name="T">The type of the result elements.</typeparam>
		Task ListAsync<T>(IList<T> results, CancellationToken cancellationToken = default(CancellationToken));

		/// <summary>
		/// Get the results.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <returns>The results.</returns>
		/// <typeparam name="T">The type of the result elements.</typeparam>
		Task<IList<T>> ListAsync<T>(CancellationToken cancellationToken = default(CancellationToken));

		/// <summary>
		/// Strongly-typed version of <see cref="UniqueResult()" />.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		Task<T> UniqueResultAsync<T>(CancellationToken cancellationToken = default(CancellationToken));

		#endregion
	}
}
