//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Mapping.ByCode;
using NUnit.Framework;
using NHibernate.Linq;

namespace NHibernate.Test.NHSpecificTest.GH2563
{
	using System.Threading.Tasks;
	[TestFixture]
	public class ByCodeFixtureAsync : TestCaseMappingByCode
	{
		protected override HbmMapping GetMappings()
		{
			var mapper = new ModelMapper();
			mapper.Class<Entity>(
				rc =>
				{
					rc.Id(x => x.Id, m => m.Generator(Generators.Assigned));
					rc.Property(x => x.Name, m => m.Lazy(true));
					rc.ManyToOne(x => x.Child);
					rc.ManyToOne(x => x.Parent);
				});

			return mapper.CompileMappingForAllExplicitlyAddedEntities();
		}

		protected override void OnSetUp()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				var e1 = new Entity { Id = 1, Name = "Middle", };
				e1.Parent = new Entity { Id = 2, Name = "Parent", Child = e1 };

				session.Save(e1);
				session.Save(e1.Parent);

				transaction.Commit();
			}
		}

		protected override void OnTearDown()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				session.CreateQuery("delete from System.Object").ExecuteUpdate();
				transaction.Commit();
			}
		}

		[Test]
		public async Task SerializationOfConnectedEntitiesWithLazyPropertiesAsync()
		{
			using (var session = OpenSession())
			{
				var result = await (session.Query<Entity>().ToListAsync());
				var ds = SpoofSerialization(session);
			}
		}

		private T SpoofSerialization<T>(T session)
		{
			var formatter = new BinaryFormatter();
			var stream = new MemoryStream();
			formatter.Serialize(stream, session);

			stream.Position = 0;
			return (T) new BinaryFormatter().Deserialize(stream);
		}
	}
}
